#!/bin/sh

set -ex

export DH_GOLANG_EXCLUDES="integration plugins/sample plugins/main/windows"

dh_auto_configure -O--buildsystem=golang -O--builddirectory=_build
dh_auto_build -O--buildsystem=golang -O--builddirectory=_build

ln -sf /usr/sbin/iptables-legacy $(pwd)/_build/bin/iptables
export PATH=$(pwd)/_build/bin:$PATH

dh_auto_test -O--buildsystem=golang -O--builddirectory=_build --no-parallel -- -timeout 30m

ip netns list| grep cnitest | cut -d' ' -f1 | xargs -n1 ip netns delete || true
